import React, { useEffect, useState } from 'react';
import { ChildProcess, Command } from '@tauri-apps/api/shell';
import './App.css';
import ScrollList from './components/ScrollList/ScrollList.component';

const App = () => {
  const [processes, setProcesses] = useState<ChildProcess>();
  const [openBlackListedApps, setOpenBlackListedApps] = useState<ChildProcess["stdout"][]>();

  const stringToList = (a: string) => {
    a = a.replace("[", '');
    a = a.replace("]", "");
    a = a.replace("/'/g", "");
    let aList = a.split(",");
    return aList as string[];
  };

  useEffect(() => {
    (async () => {
      const command = Command.sidecar('../src-python/dist/checkRunningProcesses');
      const output = await command.execute();
      console.log(output);
      setProcesses(output);
      let stdout = stringToList(output.stdout);
      setOpenBlackListedApps(stdout);
    })();
  }, []);

  return (
    <div className="App">
      <header className="App-header">
        <div>
        <div>You have {openBlackListedApps?.length} blacklisted apps open</div>
        {openBlackListedApps ?  <ScrollList data={openBlackListedApps} /> : null}
        <div>Please close them to take the test</div>
        </div>
      </header>
    </div>
  );
}

export default App;


// TestID -> Given to the student
// Email -> take from log in
// Timestamp -> autogenerated
// Uid -> autogenerated

// Run it every 1 minute
